project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 4"
          href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
    - text: "Take-home Exercises"
      menu:
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"   
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 3_01"
          href: "Hands-on_Ex/Hands-on_Ex03_01/Hands-on_Ex03_01.html"
        - text: "Hands-on Exercise 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Hands-on Exercise 4_01"
          href: "Hands-on_Ex/Hands-on_Ex04_01/Hands-on_Ex04_01.html"
        - text: "Hands-on Exercise 4_02"
          href: "Hands-on_Ex/Hands-on_Ex04_02/Hands-on_Ex04_02.html"
        - text: "Hands-on Exercise 4_03"
          href: "Hands-on_Ex/Hands-on_Ex04_03/Hands-on_Ex04_03.html"
        - text: "Hands-on Exercise 5"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
        - text: "Hands-on Exercise 5_01"
          href: "Hands-on_Ex/Hands-on_Ex05_01/Hands-on_Ex05_01.html"
        - text: "Hands-on Exercise 5_02"
          href: "Hands-on_Ex/Hands-on_Ex05_02/Hands-on_Ex05_02.html"
        - text: "Hands-on Exercise 5_03"
          href: "Hands-on_Ex/Hands-on_Ex05_03/Hands-on_Ex05_03.html"
        - text: "Hands-on Exercise 5_04"
          href: "Hands-on_Ex/Hands-on_Ex05_04/Hands-on_Ex05_04.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd
      
format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual
